# Generated by Django 4.2 on 2024-03-05 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='books.category')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pageCount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('publishedDate', models.DateTimeField(auto_now_add=True)),
                ('thumbnailUrl', models.ImageField(upload_to='books/')),
                ('shortDescription', models.CharField(max_length=1000)),
                ('longDescription', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='author_of_book', to='books.author')),
                ('categories', models.ManyToManyField(related_name='category_of_book', to='books.category')),
            ],
        ),
    ]
